version: '3'

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        ports:
            - "80:80"
        volumes:
            - static_volume:/app/backend/static
            - ./docker/nginx/development:/etc/nginx/conf.d
        depends_on:
            - backend
            - frontend
    backend:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/backend/Dockerfile
        entrypoint: /app/docker/backend/wsgi-entrypoint.sh
        volumes:
            - static_volume:/app/backend/static
        ports:
            - "8000:8000"

    frontend:
        restart: unless-stopped

        build:
            context: .
            dockerfile: ./docker/frontend/Dockerfile
        volumes:
            - node_modules:/app/frontend/node_modules
        ports:
            - "3000:3000"

volumes:
    static_volume: {}
    node_modules: {}